web:
    image: nginx:latest
    ports:
        - "8082:80"
    volumes:
        - ./sources:/sources
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

php:
    image: php:7-fpm
    volumes:
        - ./sources:/sources
        
#http://geekyplatypus.com/making-your-dockerised-php-application-even-better/